plugins {
    alias(libs.plugins.android.application)
}
def getIpAddress() {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    return properties.getProperty('ip_addr')
}

android {
    namespace 'rs.ac.uns.eventplanner.team7'
    compileSdk 34

    defaultConfig {
        applicationId "rs.ac.uns.eventplanner.team7"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"
        android.buildFeatures.buildConfig true
        buildConfigField "String", "IP_ADDR", "\"" + getIpAddress()+"\""
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation libs.lombok
    implementation libs.appcompat
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.annotation
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.1'
    implementation("com.kizitonwose.calendar:view:2.6.1")
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // for JSON parsing
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

}